# Generated by Django 4.1.5 on 2023-01-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karavanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('karavanModeli', models.CharField(max_length=200, verbose_name='Karavan Modeli')),
                ('aciklama', models.TextField(max_length=200, verbose_name='Karavan Detayı')),
            ],
        ),
    ]
