# Generated by Django 4.1.5 on 2023-01-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0003_bungalov'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadirModeli', models.CharField(max_length=50, verbose_name='Çadır Modeli')),
                ('aciklama', models.TextField(max_length=200, verbose_name='Çadır Hakkında Detaylar')),
                ('image', models.FileField(null=True, upload_to='', verbose_name='')),
            ],
        ),
        migrations.AlterField(
            model_name='bungalov',
            name='aciklama',
            field=models.TextField(max_length=200, verbose_name='Bungalov Detayı'),
        ),
    ]
