# Generated by Django 4.1.5 on 2023-01-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0004_tent_alter_bungalov_aciklama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tent',
            name='image',
            field=models.FileField(null=True, upload_to='', verbose_name='Çadır Resmi'),
        ),
    ]
