# Generated by Django 4.1.5 on 2023-01-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0005_alter_tent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Yorum Yapan Kişi')),
                ('title', models.CharField(max_length=50, verbose_name='Yorum Başlığı')),
                ('text', models.TextField(max_length=200, verbose_name='Yorum')),
                ('date_now', models.DateTimeField(verbose_name='yorum yapılma zamanı')),
                ('bungalov_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.bungalov', verbose_name='Bungalov Yorumları')),
                ('cadir_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.tent', verbose_name='Çadır Yorumları')),
                ('karavan_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.karavanlar', verbose_name='Karavan Yorumları')),
            ],
        ),
    ]
