# Generated by Django 4.1.5 on 2023-01-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bungalov_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.bungalov', verbose_name='Bungalov Yorumları'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cadir_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.tent', verbose_name='Çadır Yorumları'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='karavan_comment',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.karavanlar', verbose_name='Karavan Yorumları'),
        ),
    ]
