# Generated by Django 4.1.5 on 2023-01-27 18:05

import appDogadaTatil.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0008_alter_comment_bungalov_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bungalov_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cadir_comment',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='karavan_comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='category',
            field=models.IntegerField(choices=[(1, appDogadaTatil.models.Karavanlar), (2, appDogadaTatil.models.Bungalov), (3, appDogadaTatil.models.Tent)], null=True),
        ),
    ]
