# Generated by Django 4.1.5 on 2023-01-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0009_remove_comment_bungalov_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='category',
            field=models.IntegerField(choices=[(1, 'Karavanlar'), (2, 'Bungalov'), (3, 'Tent')], null=True),
        ),
    ]
