# Generated by Django 4.1.5 on 2023-01-27 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0010_alter_comment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
        migrations.CreateModel(
            name='AllProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bungalovlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.bungalov', verbose_name='')),
                ('cadirlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.tent', verbose_name='')),
                ('karavanlar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.karavanlar', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='allproducts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.allproducts', verbose_name=''),
        ),
    ]
