# Generated by Django 4.1.5 on 2023-01-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0012_remove_comment_allproducts_comment_karavan_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='karavan_category',
            field=models.ManyToManyField(to='appDogadaTatil.karavanlar', verbose_name='Karavan Modelleri'),
        ),
    ]
