# Generated by Django 4.1.5 on 2023-01-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0014_comment_bungalov_category_comment_tent_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='bungalov_category',
            field=models.ManyToManyField(blank=True, to='appDogadaTatil.bungalov', verbose_name='Bungalov Modelleri'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='karavan_category',
            field=models.ManyToManyField(blank=True, to='appDogadaTatil.karavanlar', verbose_name='Karavan Modelleri'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tent_category',
            field=models.ManyToManyField(blank=True, to='appDogadaTatil.tent', verbose_name='Çadır Modelleri'),
        ),
    ]
