# Generated by Django 4.1.5 on 2023-01-27 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0015_alter_comment_bungalov_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='bungalov_category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='karavan_category',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tent_category',
        ),
        migrations.AddField(
            model_name='comment',
            name='bungalov_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.bungalov', verbose_name='Bungalov Modelleri'),
        ),
        migrations.AddField(
            model_name='comment',
            name='karavan_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.karavanlar', verbose_name='Karavan Modelleri'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appDogadaTatil.tent', verbose_name='Çadır Modelleri'),
        ),
    ]
