# Generated by Django 4.1.5 on 2023-01-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0016_remove_comment_bungalov_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_now',
            field=models.DateTimeField(auto_now_add=True, verbose_name='yorum yapılma zamanı'),
        ),
    ]
