# Generated by Django 4.1.5 on 2023-02-01 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0017_alter_comment_date_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karavanlar',
            options={'verbose_name_plural': 'Meta Class Denemesi: Karavanlar'},
        ),
    ]
