# Generated by Django 4.1.5 on 2023-02-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0019_alter_bungalov_options_alter_karavanlar_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='karavanlar',
            name='url_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Url yönlendirmesi için gerekli alan'),
        ),
    ]
