# Generated by Django 4.1.5 on 2023-02-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0020_karavanlar_url_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bungalov',
            name='url_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Url yönlendirmesi için gerekli alan'),
        ),
        migrations.AddField(
            model_name='tent',
            name='url_name',
            field=models.CharField(max_length=50, null=True, verbose_name='Url yönlendirmesi için gerekli alan'),
        ),
    ]
