# Generated by Django 4.1.5 on 2023-02-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDogadaTatil', '0021_bungalov_url_name_tent_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bungalov',
            name='url_name',
        ),
        migrations.RemoveField(
            model_name='karavanlar',
            name='url_name',
        ),
        migrations.RemoveField(
            model_name='tent',
            name='url_name',
        ),
    ]
